I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/chapter-1.rpy", line 99, in script
    P "HIDE!"
Exception: Sayer 'P' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/chapter-1.rpy", line 99, in script
    P "HIDE!"
  File "renpy/ast.py", line 680, in execute
    who = eval_who(self.who, self.who_fast)
  File "renpy/ast.py", line 574, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'P' is not defined.

Windows-10-10.0.19041
Ren'Py 7.4.2.1292
Time Travel Game V01 1.0
Sat Mar 13 19:46:42 2021
